// src/lib/components/atoms/switch/switch.tsx
import { s, sm } from "#/lib/utils/style/class";
import type { SwitchProps } from "./switch.type";
import type { KeyboardEvent } from "react";
import { forwardRef, useEffect, useState } from "react";

export const Switch = forwardRef<HTMLInputElement, SwitchProps>(({ className, disabled, checked, ...props }, ref) => {
  const [isChecked, setIsChecked] = useState(checked || false);

  useEffect(() => setIsChecked(checked || false), [checked]);

  // Styles :
  const styles = sm(
    "relative w-11 h-5 appearance-none focus:ring-2 focus:ring-primary-500 rounded-full outline-none",
    {
      "cursor-pointer": !disabled,
      "brightness-75": disabled
    },
    className
  );

  const handleEnter = (event: KeyboardEvent): void => {
    if (event.key !== "Enter" || disabled) return;
    setIsChecked((state) => !state);
  };

  const handleClick = (): void => {
    if (disabled) return;
    setIsChecked((state) => !state);
  };

  return (
    <button className={styles} onClick={handleClick}>
      <input
        aria-checked={isChecked}

        ref={ref}
        type="checkbox"
        className="appearance-none opacity-0 outline-none"
        checked={isChecked}
        disabled={disabled}
        onKeyDown={handleEnter}
        {...props}  />

      <span className={s(
        "absolute top-0 left-0 right-0 bottom-0 transition-all rounded-full",
        "before:absolute before:content=[''] before:h-4 before:w-4 before:bg-white before:rounded-full before:transition-transform",
        "before:top-0.5 before:left-0.5",
        {
          "bg-gray-500": !isChecked,
          "bg-primary-500": isChecked,

          "before:translate-x-6": isChecked
        }
      )}></span>
    </button>
  );
});

Switch.displayName = "Switch";

// src/libraries/components/form/switch/switch.svelte
<script lang="ts">
  import { clsx } from "clsx";
  import type { SwitchColor } from "./switch.type";
  import { Text } from "../../texts/text";

  // Props :
  export let color: SwitchColor = "primary";
  export let label: string | null = null;

  let checked: boolean = false;

  // Style :
  $: style = clsx("shadow w-11 h-6 rounded-full peer-focus:ring after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all", {
    // Color :
    "bg-gray-2": !checked,
    "bg-primary-1": color === "primary" && checked,
    "bg-secondary-1": color === "secondary" && checked,
    "bg-success-1": color === "success" && checked,
    "bg-warning-1": color === "warning" && checked,
    "bg-error-1": color === "error" && checked,

    "peer-focus:ring-primary-1/50": color === "primary",
    "peer-focus:ring-secondary-1/50": color === "secondary",
    "peer-focus:ring-success-1/50": color === "success",
    "peer-focus:ring-warning-1/50": color === "warning",
    "peer-focus:ring-error-1/50": color === "error",

    // Position :
    "after:translate-x-full after:border-white": checked
  });
</script>

<label class="inline-flex relative items-center cursor-pointer">
  <input type="checkbox" class="sr-only peer" bind:checked={checked}>
  <div class={style}></div>

  {#if label}
    <div class="ml-2">
        <Text type="p" size="small">{label}</Text>
    </div>
  {/if}
</label>
