// app/sections/header.section.tsx
import { LinkButton } from "@lib/components/atomics/button/button";
import { Text } from "@lib/components/atomics/texts";
import { Heading } from "@lib/components/atomics/texts/heading";
import Image from "next/image";
import { ReactElement } from "react";
import { BsDiscord } from "react-icons/bs";

export const HeaderSection = (): ReactElement => {
  return (
    <header className="container grid grid-cols-2 items-center mt-28">
      <div className="relative">
        <Heading type="h1" className="uppercase font-extrabold">Le Royaume</Heading>
        <Text>Rejoignez notre communauté de développeurs talentueux ou devenez le !</Text>
        <LinkButton href="/register" className="mt-4">
          <BsDiscord />
          Rejoindre
        </LinkButton>
      </div>
      <div className="justify-self-end relative">
        <Image alt="crown" src="/images/crown.png" className="relative z-10" height={500} width={500} />
        <span className="absolute -top-32 right-0 h-[35rem] w-[35rem] rounded-full blur-3xl opacity-30 right-0 bg-purple rounded-full" />
      </div>
    </header>
  );
}

// src/routes/header.section.svelte
<script>
    import { BrandDiscord } from "$lib/components/icons";

</script>
<div class="flex sm:flex-row flex-col mx-auto w-full justify-center items-center">
  <div class="mt-16 px-6 md:mt-10 basis-1/2 flex flex-col justify-center mr-5">
    <h3 class="font-black text-white text-xl md:text-2xl">LE ROYAUME</h3>
    <p class="text-white font-extralight md:text-1xl">Rejoignez notre communauté de développeurs talentueux ou devenez le prochain.</p>

    <a href="/discord/pro" class="gap-3 w-36 mt-5 bg-discord-primary hover:bg-discord-primary-2 transition-colors text-white text-normal font-semibold py-1 px-3 rounded-lg flex items-center">
      <BrandDiscord />
      <!-- https://github.com/tabler/tabler-icons/issues/608 -->
      Rejoindre
    </a>
  </div>

  <div class="mt-10 bg-blue-500 rounded-full w-64 h-64 hidden md:flex justify-center items-center">
    <img src="https://cdn.discordapp.com/attachments/1064617747008471180/1091085620400631908/crownn_1-removebg-preview.png" alt="tgm">
  </div>
</div>
