// src/lib/components/layouts/navbar/navbar.svelte
<script lang="ts">
  import type { Page } from "./navbar.type";

  export let pages: Page[];
</script>

<div class="p-2 bg-[#000000]/50 fixed h-16 w-full backdrop-blur-md">
  <div class="flex mt-2 items-center justify-between mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="icon">
      <a href="/">
        <img src="/images/royaume-logo.png" alt="Logo" class="h-8 w-8" />
      </a>
    </div>
    <ul class="flex items-center gap-4 text-white">
      {#each pages as page}
        <li>
          <a href="/{page.link}" target={page.target} class="flex -mt-1 focus:outline-none">{page.name}</a>
        </li>
      {/each}
    </ul>
  </div>
</div>

// lib/components/molecules/navbar/navbar.tsx
import { links } from "@lib/configs/navbar/navbar.config";
import { ReactElement } from "react";
import Image from "next/image";
import Link from "next/link";

export const Navbar = (): ReactElement => {
  return (
    <nav className="fixed top-0 right-0 left-0 z-50 bg-background-header backdrop-blur-2xl py-3">
      <div className="flex justify-between flex container items-center">
        <Image src="/images/royaume-logo.png" alt="logo" width={50} height={50} />
        <ul className="flex gap-10">
          {links.map((link) => (
            <Link key={link.name} href={link.href} className="text-white">{link.name}</Link>
          ))}
        </ul>
      </div>
    </nav>
  )
}

export default Navbar;
